// File: ./back/src/types/declarations.d.ts
declare module 'pg';
declare module 'ws';
declare module 'jsonwebtoken';
declare module 'cookie-parser';
declare module 'express-useragent';
declare module 'ioredis';
declare module 'morgan';
declare module 'redis';